export interface DailyEntry {
  date: string // format YYYY-MM-DD
  capital: number // capital total ce jour
  note?: string
}

// Configuration initiale du PEA
export interface InitialConfig {
  startDate: string // date de début de suivi
  startCapital: number // capital à cette date
  startDeposited: number // total déjà versé à cette date
}

// Versement ponctuel
export interface Deposit {
  id: string
  date: string // format YYYY-MM-DD
  amount: number
  isAutoGenerated?: boolean // true si généré par DCA
}

// Configuration DCA
export interface DCAConfig {
  enabled: boolean
  amount: number // montant par versement
  dayOfMonth1: number // premier jour du mois (1-28)
  dayOfMonth2?: number // deuxième jour optionnel (1-28)
  adjustWeekend: 'before' | 'after' | 'none' // décaler si weekend
}

// Données calculées pour un jour
export interface DayPerformance {
  date: string
  capital: number
  previousCapital: number
  depositsOfDay: number
  gainAmount: number // en €
  gainPercent: number // en %
}

export interface MonthData {
  year: number
  month: number // 0-11
}

export type DayStatus = 'positive' | 'negative' | 'neutral' | 'empty'
